### ISSUE TITLE
Failed to find remote path

### ISSUE THREAD

**Issue by rmkjr** [omriiluz/gdrive-sync#4]
I'm sure I am just missing something small.

I ran "gsync list /root/test /testfolder", where "testfolder" is a directory in the root of my gdrive.
and get back
"list /root/test to /testfolder
Failed to find remote path - does not exist"

I tried a few different paths and even the folder id, but always the same message.

Thanks in advance.

**Comment by omriiluz** [comment]
try to remove the leading "/" before "/testfolder", this should do the trick.

**Comment by rmkjr** [comment]
Still seeing the same issue.  Maybe a bit more info would be useful, this is my first insight into node so I am still getting used to things.  I am running this on a synology with their node package (v0.10).  To install I ran "npm install gdrive-sync -g".  I ran through the auth, got my key and supplied it to the prompt.  Here is what I am seeing from the test function as well as removing the / in the drive path as recommended.

<pre>
DS-1> ls
test
DS-1> node /usr/lib/node_modules/gdrive-sync sync test testfolder
list test to testfolder
Failed to find remote path - does not exist
DS-1> node /usr/lib/node_modules/gdrive-sync test
test
Total
{ [Error: ENOENT, open 'c:/temp/2.bin'] errno: 34, code: 'ENOENT', path: 'c:/temp/2.bin' }
/volume1/@appstore/Node.js/usr/lib/node_modules/gdrive-sync/gsync.js:492
            var req=c.authClient.transporter.innerRequest;
                                ^
TypeError: Cannot read property 'transporter' of undefined
    at /volume1/@appstore/Node.js/usr/lib/node_modules/gdrive-sync/gsync.js:492:24
    at fs.js:208:20
    at Object.oncomplete (fs.js:108:15)
</pre>

Thanks for taking the time to help, really excited to get this going in some scripts.

**Comment by omriiluz** [comment]
I made a few updates and bugfixes, can you please try again now?

**Comment by arodic** [comment]
I just run into the same issue with the latest fixes. FYI
